import type { Preset } from '../types/presets';
import { createDefaultRackState } from '../types/rack';

export const FACTORY_PRESETS: Preset[] = [
  {
    id: 'factory-clean',
    name: 'Clean',
    isFactory: true,
    chain: [
      { type: 'compressor', bypassed: false, params: { threshold: -20, ratio: 2, attack: 0.01, release: 0.25, makeup: 3 } },
      { type: 'eq', bypassed: false, params: { lowGain: 0, midGain: -2, midFreq: 1000, highGain: 2 } },
      { type: 'volume', bypassed: false, params: { gain: 100 } },
    ],
    rack: createDefaultRackState(),
    category: 'Clean',
    tags: ['factory', 'clean', 'studio'],
    description: 'Balanced clean foundation with light compression and a polished top end.',
    notes: '',
    favorite: false,
  },
  {
    id: 'factory-crunch',
    name: 'Crunch',
    isFactory: true,
    chain: [
      { type: 'compressor', bypassed: false, params: { threshold: -18, ratio: 3, attack: 0.005, release: 0.2, makeup: 4 } },
      { type: 'distortion', bypassed: false, params: { drive: 35, tone: 3500, level: 55, mode: 0 } },
      { type: 'eq', bypassed: false, params: { lowGain: 1, midGain: 2, midFreq: 800, highGain: -1 } },
      { type: 'delay', bypassed: false, params: { time: 120, feedback: 15, mix: 20 } },
      { type: 'volume', bypassed: false, params: { gain: 100 } },
    ],
    rack: createDefaultRackState(),
    category: 'Crunch',
    tags: ['factory', 'crunch', 'rock'],
    description: 'Mid-forward breakup with compact ambience for classic rhythm parts.',
    notes: '',
    favorite: false,
  },
  {
    id: 'factory-lead',
    name: 'Lead',
    isFactory: true,
    chain: [
      { type: 'compressor', bypassed: false, params: { threshold: -24, ratio: 4, attack: 0.003, release: 0.25, makeup: 6 } },
      { type: 'distortion', bypassed: false, params: { drive: 70, tone: 4000, level: 50, mode: 2 } },
      { type: 'eq', bypassed: false, params: { lowGain: -2, midGain: 4, midFreq: 1200, highGain: 1 } },
      { type: 'delay', bypassed: false, params: { time: 400, feedback: 35, mix: 30 } },
      { type: 'reverb', bypassed: false, params: { decay: 1.5, mix: 20, brightness: 60 } },
      { type: 'volume', bypassed: false, params: { gain: 100 } },
    ],
    rack: createDefaultRackState(),
    category: 'Lead',
    tags: ['factory', 'lead', 'solo'],
    description: 'Focused sustain and delay support for melodic lead playing.',
    notes: '',
    favorite: false,
  },
  {
    id: 'factory-ambient',
    name: 'Ambient',
    isFactory: true,
    chain: [
      { type: 'compressor', bypassed: false, params: { threshold: -20, ratio: 2, attack: 0.02, release: 0.3, makeup: 4 } },
      { type: 'chorus', bypassed: false, params: { rate: 0.8, depth: 60, mix: 50 } },
      { type: 'delay', bypassed: false, params: { time: 600, feedback: 55, mix: 45 } },
      { type: 'reverb', bypassed: false, params: { decay: 5, mix: 55, brightness: 40 } },
      { type: 'tremolo', bypassed: false, params: { rate: 1.5, depth: 25, wave: 0 } },
      { type: 'volume', bypassed: false, params: { gain: 100 } },
    ],
    rack: createDefaultRackState(),
    category: 'Ambient',
    tags: ['factory', 'ambient', 'space'],
    description: 'Wide modulation and long tails for expansive textures.',
    notes: '',
    favorite: false,
  },
  {
    id: 'factory-heavy',
    name: 'Heavy',
    isFactory: true,
    chain: [
      { type: 'compressor', bypassed: false, params: { threshold: -30, ratio: 8, attack: 0.001, release: 0.15, makeup: 8 } },
      { type: 'distortion', bypassed: false, params: { drive: 90, tone: 3000, level: 60, mode: 1 } },
      { type: 'eq', bypassed: false, params: { lowGain: 3, midGain: -4, midFreq: 600, highGain: 2 } },
      { type: 'volume', bypassed: false, params: { gain: 100 } },
    ],
    rack: createDefaultRackState(),
    category: 'Heavy',
    tags: ['factory', 'heavy', 'gain'],
    description: 'High-gain contour with scooped mids and strong compression.',
    notes: '',
    favorite: false,
  },
  {
    id: 'factory-surf',
    name: 'Surf',
    isFactory: true,
    chain: [
      { type: 'tremolo', bypassed: false, params: { rate: 6, depth: 70, wave: 0 } },
      { type: 'reverb', bypassed: false, params: { decay: 1.8, mix: 45, brightness: 70 } },
      { type: 'volume', bypassed: false, params: { gain: 100 } },
    ],
    rack: createDefaultRackState(),
    category: 'Vintage',
    tags: ['factory', 'surf', 'spring'],
    description: 'Bright tremolo and reverb splash for vintage-style rhythm lines.',
    notes: '',
    favorite: false,
  },
];
